run:
  tests: false

linters:
  disable:
    - deadcode
    - varcheck
    - unused
  enable:
    - gosec

issues:
  exclude-rules:
    - text: "G505"
      linters:
        - gosec
    - text: "G401"
      linters:
        - gosec